### ISSUE TITLE
Error using Closure Actions

### ISSUE THREAD

**Issue by indieNik** [wecatch/ember-cli-simditor#10]
For some reason, I was running into issues with this closure actions:

`{{simditor-editor value=model update=(action (mut model.content)) editor=(mut editor) onValuechanged=(action "valuechanged") }}`

Error I was getting:
```
Assertion Failed: An action named 'valuechanged' was not found in (generated post controller)
Error
    at assert (http://localhost:4200/assets/vendor.js:18616:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:18829:34)
    at makeClosureAction (http://localhost:4200/assets/vendor.js:22776:21)
    at exports.default (http://localhost:4200/assets/vendor.js:22703:12)
    at CompiledHelper.evaluate (http://localhost:4200/assets/vendor.js:11781:17580)
    at CompiledNamedArgs.evaluate (http://localhost:4200/assets/vendor.js:11684:9089)
    at CompiledArgs.evaluate (http://localhost:4200/assets/vendor.js:11684:12486)
    at http://localhost:4200/assets/vendor.js:11684:14736
    at AppendOpcodes.evaluate (http://localhost:4200/assets/vendor.js:11683:2168)
    at VM.next (http://localhost:4200/assets/vendor.js:11938:872)
```
So I switched it to default action:

`{{simditor-editor value=model update=(action (mut model.content)) editor=(mut editor) action="valuechanged" }}`

And finally got it to work.

Any thoughts on this?

**Comment by zhyq0826** [comment]
@indieNik what's your ember version?

**Comment by indieNik** [comment]
$ ember -v
ember-cli: 2.11.0
node: 6.9.5
os: win32 x64

@zhyq0826 FYI

**Comment by zhyq0826** [comment]
@indieNik  Clone this repository, then run `ember server`, if the dummy app works well, the closure action will work well. I have test on linux and macOS。

**Comment by indieNik** [comment]
@zhyq0826  Sure. Will give it a try!
